name: BreakGuard Bug / Feedback
description: Report incorrect results, missing call sites, crashes, or general feedback
title: "[BreakGuard] "
labels: ["bug", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using **BreakGuard**.

        Please **do not paste source code, file paths, or private repository details** unless absolutely necessary.
        The diagnostics section below may be auto-filled by the extension and is anonymized.

  - type: textarea
    id: intent
    attributes:
      label: What were you trying to do?
      description: Briefly describe the change or analysis you were performing.
      placeholder: "Example: I changed a function signature to see what downstream code would break."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What happened?
      description: What did BreakGuard report or do that seemed incorrect or unexpected?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What result would you have expected instead?
    validations:
      required: true

  - type: checkboxes
    id: issue_type
    attributes:
      label: Issue category (check all that apply)
      options:
        - label: Missed a breaking change
        - label: Reported a breaking change that wasn't real
        - label: Call sites missing or incorrect
        - label: Incorrect downstream impact
        - label: Performance issue
        - label: Error or crash
        - label: UI / usability issue
        - label: General feedback

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics (auto-filled)
      description: |
        This section may be pre-filled by the extension with anonymized version,
        environment, and usage summary. You may remove or edit it.
      render: text
    validations:
      required: false
