name: BreakGuard Feature Request
description: Suggest an idea or improvement for BreakGuard
title: "[BreakGuard] "
labels: ["enhancement", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

        You don't need to design the solution - describing the problem is enough.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: What's currently hard, slow, or error-prone when using BreakGuard?
      placeholder: "Example: I can see breaking changes, but I still have to manually track where fixes are needed."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: When does this problem show up?
      description: Describe the workflow or situation where this becomes painful.
      placeholder: "Example: Large monorepo with shared UI utilities."
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: Any ideas on how this could work? (optional)
      description: Optional - feel free to skip this if you're not sure.
    validations:
      required: false
